// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Online Checklists",
    "title": "Checklists",
    "version": "0.0.1"
  },
  "paths": {
    "/healthcheck": {
      "get": {
        "tags": [
          "healthcheck"
        ],
        "responses": {
          "200": {
            "description": "confirm that the service is healthy"
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/errorMessage"
            }
          }
        }
      }
    },
    "/user": {
      "get": {
        "responses": {
          "200": {
            "$ref": "#/definitions/user"
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/errorMessage"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "errorMessage": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "user": {
      "type": "object",
      "required": [
        "first",
        "last",
        "username",
        "email",
        "role",
        "active"
      ],
      "properties": {
        "active": {
          "type": "boolean"
        },
        "email": {
          "type": "string",
          "minLength": 1
        },
        "first": {
          "type": "string",
          "minLength": 0
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "last": {
          "type": "string",
          "minLength": 1
        },
        "role": {
          "type": "integer",
          "format": "int64"
        },
        "username": {
          "type": "string",
          "minLength": 3
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Online Checklists",
    "title": "Checklists",
    "version": "0.0.1"
  },
  "paths": {
    "/healthcheck": {
      "get": {
        "tags": [
          "healthcheck"
        ],
        "responses": {
          "200": {
            "description": "confirm that the service is healthy"
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/errorMessage"
            }
          }
        }
      }
    },
    "/user": {
      "get": {
        "responses": {
          "200": {},
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/errorMessage"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "errorMessage": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "user": {
      "type": "object",
      "required": [
        "first",
        "last",
        "username",
        "email",
        "role",
        "active"
      ],
      "properties": {
        "active": {
          "type": "boolean"
        },
        "email": {
          "type": "string",
          "minLength": 1
        },
        "first": {
          "type": "string",
          "minLength": 0
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "last": {
          "type": "string",
          "minLength": 1
        },
        "role": {
          "type": "integer",
          "format": "int64"
        },
        "username": {
          "type": "string",
          "minLength": 3
        }
      }
    }
  }
}`))
}
