swagger: "2.0"
info:
  description: Online Checklists
  title: Checklists
  version: 0.0.1
produces:
- application/json
consumes:
- application/json
schemes:
- http
definitions:
  $ref: './definitions/index.yml'
paths:
  $ref: './paths/index.yml'
