// Code generated by go-swagger; DO NOT EDIT.

package healthcheck

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/mkandel/checklists_swagger/models"
)

// GetHealthcheckOKCode is the HTTP code returned for type GetHealthcheckOK
const GetHealthcheckOKCode int = 200

/*GetHealthcheckOK confirm that the service is healthy

swagger:response getHealthcheckOK
*/
type GetHealthcheckOK struct {
}

// NewGetHealthcheckOK creates GetHealthcheckOK with default headers values
func NewGetHealthcheckOK() *GetHealthcheckOK {

	return &GetHealthcheckOK{}
}

// WriteResponse to the client
func (o *GetHealthcheckOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*GetHealthcheckDefault generic error response

swagger:response getHealthcheckDefault
*/
type GetHealthcheckDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorMessage `json:"body,omitempty"`
}

// NewGetHealthcheckDefault creates GetHealthcheckDefault with default headers values
func NewGetHealthcheckDefault(code int) *GetHealthcheckDefault {
	if code <= 0 {
		code = 500
	}

	return &GetHealthcheckDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get healthcheck default response
func (o *GetHealthcheckDefault) WithStatusCode(code int) *GetHealthcheckDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get healthcheck default response
func (o *GetHealthcheckDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get healthcheck default response
func (o *GetHealthcheckDefault) WithPayload(payload *models.ErrorMessage) *GetHealthcheckDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get healthcheck default response
func (o *GetHealthcheckDefault) SetPayload(payload *models.ErrorMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHealthcheckDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
