# DB:
# Tables:
#     checklists:
#         - checklist_id
#         - checklist_name
#         - checklist_template
#         - checklist_creator
#         - checklist_owner
#         - [ checklist_items ]
# 
#     users:
#         - user_id
#         - user_first_name
#         - user_last_name
#         - user_username
#         - user_is_admin
# 
#     items:
#         - item_id
#         - checklist_id
#         - item_name
#         - item_checked - 0 if not checked, 1 if checked
#         - item_validation_routine - coderef
